# Codecov configuration file
# https://docs.codecov.com/docs/codecovyml-reference

# https://docs.codecov.com/docs/coverage-configuration
coverage:
  range: 85..100
  round: down
  status:
    project:
      default:
        threshold: 1%
      branches:
        threshold: 1%

# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "tests"
  - "src/test_utils.rs"
  - "scripts"
  - "*.md"
  - "*.toml"

# https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: "files"
  require_changes: true
