name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Config lives in 'typos.toml'
  typos:
    name: Check for typos
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Check for typos
        uses: crate-ci/typos@v1
  
  # Config lives in 'rustfmt.toml'
  cargo-fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --all -- --check

  cargo-doc:
    name: Check documentation
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check documentation
        run: cargo doc --workspace --no-deps --document-private-items

  # Config lives in 'cargo.toml'
  cargo-clippy:
    name: Check for linting issues
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check for linting issues
        run: cargo clippy --all-targets --all-features -- -D warnings

  cargo-test:
    name: Check tests
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check build
        run: cargo build --tests
      - name: Check tests
        run: cargo test --all-targets --all-features
      - name: Check doc-tests
        run: cargo test --all-features --doc
